# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MEGARAID_MM)	+= megaraid_mm.o
obj-$(CONFIG_MEGARAID_MAILBOX)	+= megaraid_mbox.o
obj-$(CONFIG_MEGARAID_SAS)	+= megaraid_sas_pdoff.o
megaraid_sas_pdoff-objs := megaraid_sas_base.o megaraid_sas_fusion.o \
	megaraid_sas_fp.o megaraid_sas_debugfs.o
